CREATE DATABASE ForumsUnknown
USE ForumsUnknown

--CREATE TABLES
CREATE TABLE FORUM_USERS
(
	UserID			INT PRIMARY KEY IDENTITY(1,1),
	UserName		VARCHAR(50) NOT NULL,
	EmailAddress	VARCHAR(255) NOT NULL,
	ProfilePicPath	NVARCHAR(255) NULL, --NEWLY ADDED
	UserPassword	VARCHAR(255) NOT NULL,
	CreatedAt		DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedAt		DATETIME DEFAULT GETDATE()
)

CREATE TABLE FORUM_POSTS
(
	PostID		INT PRIMARY KEY IDENTITY(1,1),
	Title		VARCHAR(100) NOT NULL,
	Content		TEXT NOT NULL,
	PostStatus	VARCHAR(20) NOT NULL DEFAULT 'pending', --NEWLY ADDED
	CreatedAt	DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedAt	DATETIME DEFAULT GETDATE(),
	AuthorID	INT NOT NULL REFERENCES FORUM_USERS(UserID)
)
--new table
CREATE TABLE POST_IMAGE
(
	ImageID		INT PRIMARY KEY IDENTITY(1,1),
	AltText		NVARCHAR(255),
	ImagePath	NVARCHAR(255) NOT NULL,
	PostID		INT NOT NULL REFERENCES FORUM_POSTS(PostID)
)

CREATE TABLE COMMENT
(
	CommentID	INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Content		TEXT NOT NULL,
	AuthorID	INT REFERENCES FORUM_USERS(UserID) NOT NULL,
	PostID		INT REFERENCES FORUM_POSTS(PostID) NOT NULL,
	CreatedAt	DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedAt	DATETIME DEFAULT GETDATE()
)
--new table
CREATE TABLE REPORTED_POSTS
(
	ReportID	INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PostID		INT REFERENCES FORUM_POSTS(PostID) NOT NULL,
	ReporterID	INT REFERENCES FORUM_USERS(UserID) NOT NULL,
	Reason		VARCHAR(255) NOT NULL,
	ReportedAt	DATETIME NOT NULL DEFAULT GETDATE(),
	IsResolved	BIT NOT NULL DEFAULT 0,
	ResolvedAt	DATETIME NULL
)

--INSERTION
INSERT INTO FORUM_USERS(UserName,EmailAddress,UserPassword) 
VALUES ('admin','admin@f.u','admin');


SELECT * FROM FORUM_USERS

--DROP COMMANDS

DROP DATABASE FORUMSUNKNOWN

DROP TABLE FORUM_USERS

DROP TABLE FORUM_POSTS

DROP TABLE COMMENT

TRUNCATE TABLE FORUM_USERS

TRUNCATE TABLE FORUM_POSTS

TRUNCATE TABLE COMMENT

