CREATE DATABASE ForumsUnknown
USE ForumsUnknown

CREATE TABLE FORUM_USERS
(
	UserID INT PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(50) NOT NULL,
	EmailAddress VARCHAR(255) NOT NULL,
	UserPassword VARCHAR(255) NOT NULL
)

CREATE TABLE FORUM_POSTS
(
	PostID INT PRIMARY KEY IDENTITY(1,1),
	Title VARCHAR(255) NOT NULL,
	Content TEXT NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE(),
	AuthorID INT NOT NULL REFERENCES FORUM_USERS(UserID)
)


DROP DATABASE FORUMSUNKNOWN

DROP TABLE FORUM_USERS