CREATE DATABASE ForumsUnknown
USE ForumsUnknown

CREATE TABLE FORUM_USERS
(
	UserID			INT PRIMARY KEY IDENTITY(1,1),
	UserName		VARCHAR(50) NOT NULL,
	EmailAddress	VARCHAR(255) NOT NULL,
	UserPassword	VARCHAR(255) NOT NULL,
	CreatedAt		DATETIME DEFAULT GETDATE(), ---ADDED
	ModifiedAt		DATETIME DEFAULT GETDATE()
)

CREATE TABLE FORUM_POSTS
(
	PostID		INT PRIMARY KEY IDENTITY(1,1),
	Title		VARCHAR(100) NOT NULL,
	Content		TEXT NOT NULL,
	CreatedAt	DATETIME DEFAULT GETDATE(),
	ModifiedAt	DATETIME DEFAULT GETDATE(),
	AuthorID	INT NOT NULL REFERENCES FORUM_USERS(UserID)
)

CREATE TABLE COMMENT
(
	CommentID	INT PRIMARY KEY IDENTITY NOT NULL,
	Content		TEXT NOT NULL,
	AuthorID	INT REFERENCES FORUM_USERS(UserID),
	PostID		INT REFERENCES FORUM_POSTS(PostID),
	CreatedAt	DATETIME DEFAULT GETDATE(),
	ModifiedAt	DATETIME DEFAULT GETDATE()
)

--INSERTION
INSERT INTO FORUM_USERS(UserName,EmailAddress,UserPassword) 
VALUES ('admin','admin@f.u','admin');


SELECT * FROM FORUM_USERS

--DROP COMMANDS

DROP DATABASE FORUMSUNKNOWN



DROP TABLE FORUM_USERS

DROP TABLE FORUM_POSTS

DROP TABLE COMMENT

