//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumsUnknown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int FeedbackID { get; set; }
        public int UserID { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual FORUM_USERS FORUM_USERS { get; set; }
    }
}
