//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumsUnknown.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuDBContext : DbContext
    {
        public FuDBContext()
            : base("name=ForumsUnknown")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FORUM_POSTS> FORUM_POSTS { get; set; }
        public virtual DbSet<FORUM_USERS> FORUM_USERS { get; set; }
        public virtual DbSet<COMMENT> COMMENT { get; set; }
        //public IEnumerable<object> COMMENT { get; internal set; }
    }
}
