//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumsUnknown.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FORUM_POSTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORUM_POSTS()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.POST_IMAGE = new HashSet<POST_IMAGE>();
            this.REPORTED_POSTS = new HashSet<REPORTED_POSTS>();
        }
    
        public int PostID { get; set; }

        [Required]
        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Content")]
        public string Content { get; set; }

        [DisplayName("Status")]
        public string PostStatus { get; set; }

        [DisplayName("Date Posted")]
        public System.DateTime CreatedAt { get; set; }

        public Nullable<System.DateTime> ModifiedAt { get; set; }
        
        [Required]
        public int AuthorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual FORUM_USERS FORUM_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST_IMAGE> POST_IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTED_POSTS> REPORTED_POSTS { get; set; }
    }
}
