//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumsUnknown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTED_POSTS
    {
        public int ReportID { get; set; }
        public int PostID { get; set; }
        public int ReporterID { get; set; }
        public string Reason { get; set; }
        public System.DateTime ReportedAt { get; set; }
        public bool IsResolved { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
    
        public virtual FORUM_POSTS FORUM_POSTS { get; set; }
        public virtual FORUM_USERS FORUM_USERS { get; set; }
    }
}
